Name: Compile Android APK

On:
  Push:
    Branches: [ “main”, “master” ]
  Workflow_dispatch:

Jobs:
  Build:
    Runs-on: ubuntu-latest

    Steps:
-	Name: Checkout repository
        Uses: actions/checkout@v4

-	Name: Set up JDK 17
        Uses: actions/setup-java@v4
        With:
          Java-version: ‘17’
          Distribution: ‘temurin’

-	Name: Setup Android SDK
        Uses: android-actions/setup-android@v3

-	Name: Setup Gradle
        Uses: gradle/actions/setup-gradle@v3
        With:
          Gradle-version: ‘8.2’

-	Name: Grant execute permission for gradlew
        Run: chmod +x gradlew || true

-	Name: Build APK with Gradle
        Run: gradle assembleDebug –stacktrace

-	Name: Upload APK Artifact
        Uses: actions/upload-artifact@v4
        With:
          Name: InventoryApp-Debug-APK
          Path: ‘**/build/outputs/apk/debug/*.apk’
